version: "3.9"
services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js
        - mongo-data:/data/db
        - ./mongo-audit:/var/log
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=jorycia
    networks:
      - mynetwork
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "api"
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./api/Files/Images:/API/Files/Images
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mynetwork
    env_file:
      - .env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - api
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
