version: "3.9"
services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: jorycia.ca
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./config:/tmp/docker-mailserver
      - ./config/postfix-accounts.cf:/tmp/docker-mailserver/postfix-accounts.cf:ro
      - /etc/letsencrypt/live/mail.jorycia.ca/fullchain.pem:/etc/letsencrypt/live/mail.jorycia.ca/fullchain.pem:ro
      - /etc/letsencrypt/live/mail.jorycia.ca/privkey.pem:/etc/letsencrypt/live/mail.jorycia.ca/privkey.pem:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - PERMIT_DOCKER=host
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/letsencrypt/live/mail.jorycia.ca/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/mail.jorycia.ca/privkey.pem
      - HOSTNAME=mail.jorycia.ca
      - DOMAINNAME=jorycia.ca

    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - mynetwork
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js
      - mongo-data:/data/db
      - ./mongo-audit:/var/log
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - mynetwork
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "api"
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./api/Files/Images:/API/Files/Images
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mynetwork
    env_file:
      - .env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - api
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/letsencrypt:/etc/letsencrypt
    command:
      - "rm /etc/nginx/sites-enabled/jorycia"
      - "rm /etc/nginx/sites-enabled/jorycia"
      - "ln -s /etc/nginx/sites-available/jorycia /etc/nginx/sites-enabled/jorycia"
      - "ln -s /etc/nginx/sites-available/jorycia-api /etc/nginx/sites-enabled/jorycia-api"
    depends_on:
      - client
      - api
    networks:
      - mynetwork
volumes:
  mongo-data:
  mailconfig:

networks:
  mynetwork:
